=== avadhesh-kubematics/deors-tools-filemanager/src/main/generator/sensible.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="sensible" type="Sensible"/>

    <xsd:complexType name="Sensible">
        <xsd:sequence>
            <xsd:element name="project" type="Project" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Project">
        <xsd:sequence>
            <xsd:element name="object" type="Object" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="sourceFolder" type="xsd:string" default="source"/>
        <xsd:attribute name="basePackage" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="Object">
        <xsd:sequence>
            <xsd:element name="field" type="Field" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="frameTitle" type="xsd:string" use="required"/>
        <xsd:attribute name="frameAbout" type="xsd:string" default=""/>
        <xsd:attribute name="log" type="xsd:boolean" default="false"/>
    </xsd:complexType>

    <xsd:complexType name="Field">
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="description" type="xsd:string" use="required"/>
        <xsd:attribute name="type" type="Type" use="required"/>
        <xsd:attribute name="required" type="xsd:boolean"/>
        <xsd:attribute name="readOnly" type="xsd:boolean"/>
        <xsd:attribute name="maxLength" type="xsd:int"/>
        <xsd:attribute name="minValue" type="xsd:int"/>
        <xsd:attribute name="maxValue" type="xsd:int"/>
        <xsd:attribute name="flag" type="xsd:boolean"/>
        <xsd:attribute name="maxIntegerDigits" type="xsd:int"/>
        <xsd:attribute name="maxFractionalDigits" type="xsd:int"/>
        <xsd:attribute name="negativeValuesAllowed" type="xsd:boolean"/>
    </xsd:complexType>

    <xsd:simpleType name="Type">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="SensibleString"/>
            <xsd:enumeration value="SensibleBoolean"/>
            <xsd:enumeration value="SensibleInteger"/>
            <xsd:enumeration value="SensibleLong"/>
            <xsd:enumeration value="SensibleBigDecimal"/>
            <xsd:enumeration value="SensibleDate"/>
            <xsd:enumeration value="SensibleTime"/>
            <xsd:enumeration value="SensibleDateTime"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== avadhesh-kubematics/deors-tools-filemanager/src/main/generator/FileNameSequencer.xml
<?xml version="1.0" encoding="UTF-8"?>
<sensible xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="sensible.xsd">
    <project name="deors.tools"
             basePackage="deors.tools.filemanager.filenamesequencer">
        <object name="FileNameSequencer"
                frameTitle="deors file name sequencer"
                frameAbout="About deors file name sequencer 1.0\nThis tool is part of deors file tools suite\nAuthor: deors\n\u00a9 deors 2009-2012"
                log="true">
            <field name="prefix" description="Prefix"
                   type="SensibleString" required="false" maxLength="128"/>
            <field name="offset" description="Offset"
                   type="SensibleInteger" required="false" minValue="0" maxValue="999"/>
            <field name="padding" description="Padding"
                   type="SensibleInteger" required="false" minValue="1" maxValue="5"/>
            <field name="rootDir" description="Root Directory"
                   type="SensibleString" required="true" maxLength="256"/>
            <field name="recurse" description="Recurse subdirectories"
                   type="SensibleBoolean" flag="true"/>
            <field name="applyToFiles" description="Apply to files"
                   type="SensibleBoolean" flag="true"/>
            <field name="applyToDirectories" description="Apply to directories"
                   type="SensibleBoolean" flag="true"/>
            <field name="filter" description="Filter files"
                   type="SensibleBoolean" flag="false"/>
            <field name="filterRegex" description="Filter expression"
                   type="SensibleString" maxLength="128"/>
        </object>
    </project>
</sensible>

=== avadhesh-kubematics/deors-tools-filemanager/src/main/generator/DateShifter.xml
<?xml version="1.0" encoding="UTF-8"?>
<sensible xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="sensible.xsd">
    <project name="deors.tools"
             basePackage="deors.tools.filemanager">
        <object name="DateShifter"
                frameTitle="deors date shifter"
                frameAbout="About deors date shifter 1.0\nThis tool is part of deors file tools suite\nAuthor: deors\n\u00a9 deors 2009-2011"
                log="true">
            <field name="shift" description="Time shift"
                   type="SensibleTime" required="true"/>
            <field name="rootDir" description="Root Directory"
                   type="SensibleString" required="true" maxLength="256"/>
            <field name="recurse" description="Recurse subdirectories"
                   type="SensibleBoolean" flag="true"/>
            <field name="applyToFiles" description="Apply to files"
                   type="SensibleBoolean" flag="true"/>
            <field name="applyToDirectories" description="Apply to directories"
                   type="SensibleBoolean" flag="true"/>
            <field name="filter" description="Filter files"
                   type="SensibleBoolean" flag="false"/>
            <field name="filterRegex" description="Filter expression"
                   type="SensibleString" maxLength="128"/>
        </object>
    </project>
</sensible>

=== avadhesh-kubematics/deors-tools-filemanager/src/main/generator/JPEGSorterAndRenamer.xml
<?xml version="1.0" encoding="UTF-8"?>
<sensible xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="sensible.xsd">
    <project name="deors.tools"
             basePackage="deors.tools.media">
        <object name="JPEGSorterAndRenamer"
                frameTitle="deors jpeg sorter and renamer"
                frameAbout="About deors jpeg sorter and renamer 1.0\nThis tool is part of deors media tools suite\nAuthor: deors\n\u00a9 deors 2009-2011"
                log="true">
            <field name="rootDir" description="Root Directory"
                   type="SensibleString" required="true" maxLength="256"/>
            <field name="name" description="Picture name"
                   type="SensibleString" required="true" maxLength="64"/>
            <field name="offset" description="Offset"
                   type="SensibleInteger" required="false" minValue="0" maxValue="999"/>
            <field name="sort" description="Sort files by shot date"
                   type="SensibleBoolean" flag="true"/>
            <field name="rename" description="Rename files"
                   type="SensibleBoolean" flag="true"/>
            <field name="update" description="Update modified date"
                   type="SensibleBoolean" flag="true"/>
            <field name="test" description="Test only"
                   type="SensibleBoolean" flag="false"/>
            <field name="recurse" description="Recurse subdirectories"
                   type="SensibleBoolean" flag="false"/>
            <field name="filter" description="Filter files"
                   type="SensibleBoolean" flag="false"/>
            <field name="filterRegex" description="Filter expression"
                   type="SensibleString" maxLength="128"/>
        </object>
    </project>
</sensible>
